feat: add delete_account with oauth2
Djangowon/fastapi-test pull request #10
Opened 2022-01-13 06:48 UTC by Djangowon

### Summary

- 가계부 삭제 기능 구현

### Story

- 가계부

### Changes

- 토큰 검증 후 해당 토큰의 유저정보 확인해 user_id 를 가진 account 를 삭제, 복구 할 수 있음
- 삭제시 Account 의 is_removed 1(True), default는 0(False)
- 삭제된 is_removed 가 1(True) 인 account 전체 불러오는 기능 추가
- is_removed 컬럼 -> 수정 기능 추가(복구)

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### Screenshots (Optional)

### How to test (Optional)
*How to test this PR*

2022-01-13 10:55 UTC, Jeldo requested changes

2022-01-13 10:55 UTC, Jeldo commented on app/api/account.py
> +def invalid_account():
P2: 사용되지 않는 예외는 삭제 부탁드릴께요.

2022-01-13 10:55 UTC, Jeldo commented on app/api/account.py
>      return results
P2: 존재하지 않는 account_id로 요청이 들어오는 경우도 처리해야하므로 해당 케이스에서는 not found를 돌려주는 것이 좋을 것 같습니다. 물론 서비스쪽에서도 DB에서 account_id로 특정 가계부를 찾을 수 없으면 None을 반환한다는 가정하에요.
```suggestion
    account = await read_account(account_id, token)
    if account is None:
        raise account_not_found() # 별도로 정의한다고 가정..
    return account
```

2022-01-13 10:55 UTC, Jeldo commented on app/service/account.py
> +    )
P2: account_not_found는 API 쪽에서 담당하는 에러이므로 APi쪽에서 정의하고 사용하는 것이 적절할 것 같아요. 여러 방법으로 구현할 수 있을 것 같은데,
1. 서비스에서 가계부가 없다면 None을 반환하고 API쪽에서 반환된 가계부가 None이면 account_not_found 예외 던지기
2. 서비스에서 가계부가 없으면 account_not_found 예외(HTTPException이 아닌 다른 예외타입)를 던지고, API 쪽에서는 서비스를 호출했을 때(당연히try..except 사이에서 호출) 예외가 발생하면, 다시 API만의 account_not_found 예외(HTTPException으로 구현된)를 던지는 방식
일단은 1번이 쉬운 방법인 것 같은데, 어떤게 좋을지 고민해보시고 순님과도 얘기해보시면 좋을 것 같아요.

2022-01-13 10:55 UTC, Jeldo commented on app/service/account.py
> +    return account
P1: 어차피 파이썬에서는 1 == True, 0 == False 이어서 
`account.is_removed = True`로 해도 될 것 같아요.
추가적으로 존재하지 않는 account_id에 쿼리를 하는 케이스에 대한 핸들링이 필요해 보입니다.
[Ref](https://stackoverflow.com/questions/2764017/is-false-0-and-true-1-an-implementation-detail-or-is-it-guaranteed-by-the)

2022-01-13 10:55 UTC, Jeldo commented on app/service/account.py
> +    session.commit()
P1: 여기도 위에처럼 0보다는 False로 비교해주세요.

2022-01-13 12:32 UTC, Djangowon commented on app/service/account.py
> +    session.commit()
수정했습니다~ 52ab83d

2022-01-13 12:33 UTC, Djangowon commented on app/api/account.py
> +def invalid_account():
수정했습니다! 52ab83d

2022-01-14 01:16 UTC, Jeldo commented
이전에 말씀드렸던대로 코멘트 해결하셨다면, 관련된 커밋 해쉬를 코멘트에 이어서 달아주시고 resolve 눌어주시면 감사드릴께요

2022-01-14 01:33 UTC, Djangowon commented on app/api/account.py
>      return results
수정했습니다. 
c6b0952

2022-01-14 01:34 UTC, Djangowon commented on app/service/account.py
> +    return account
수정했습니다.
c6b0952

2022-01-14 01:36 UTC, Djangowon commented on app/service/account.py
> +    )
네~ 순님과도 이야기해보고 추가로 수정있다면 수정하겠습니다. 감사합니다!
c6b0952

2022-01-14 01:56 UTC, Jeldo requested changes
서비스에서 account_not_found

2022-01-14 01:56 UTC, Jeldo commented on app/service/account.py
> +    statement = select(Account).filter(Account.user_id == user_id)
P2: read_account는 삭제 여부에 관계 없이 유저의 모든 가계부를 불러올 것 같은데 확인 부탁드릴께요.

2022-01-14 01:56 UTC, Jeldo commented on app/service/account.py
> +    )
서비스에 아직 HTTPException이 남아있는데, 서비스에서 HTTPException을 올려줄지, 아니면 쿼리시 모델이 없으면 None을 반환하고 API쪽에서 예외처리를 하는 방식으로 하는지 알려주시고 진행부탁드립니다.

2022-01-19 14:19 UTC, Jeldo requested changes

2022-01-19 14:21 UTC, Jeldo commented
분명히 이전에 다뤘던 PR로 기억했는데, 제가 코멘트는 달아놓고 요청을 안눌러서 계속 pending 상태로 있었네요...😇 늦게 드려 죄송합니다...
이전 커밋들이 머지가 되면서 지금 코드 병합시 충돌이 있는 것 같은데, 이 부분 해결해주시면 될 것 같아요.

2022-01-23 06:05 UTC, merged