feat: OAuth2 with Password, Bearer with JWT tokens
Djangowon/fastapi-test pull request #2
Opened 2022-01-04 16:33 UTC by Djangowon

### Summary

- auth.py 추가 -> 보안 비밀번호 해싱, JWT token 처리

### Story

- 이후 회원가입, 로그인 기능에 필요한 auth 세팅

### Changes

- bcrypt 이용한 비밀번호 해싱, 해시 및 암호 확인
- JWT 토큰 처리, 토큰이 유효하지 않을 시 401 반환
- 종속성 업데이트, /token 경로 작업 업데이트

### To Do
- Account 기능 구현 이후 get_user, get_current_user -> return type 테스트 후 수정
- 로그인 하면서 토큰을 발급 -> 해당 유저를 orm통해서 조회를하고 유저정보를 가져오기 구현
- 로그인 토큰을 갖고 해당 유저를 orm통해서 조회를하고 유저에 해당되는 account를 전부 가져오기 구현

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### Screenshots (Optional)

### How to test (Optional)
*How to test this PR*

2022-01-06 08:23 UTC, AhnSeongHyun requested changes

2022-01-06 08:23 UTC, AhnSeongHyun commented on app/api/auth.py
> +SECRET_KEY = 'e9ba92fd-0660-4bc2-a90b-5121bdd67ca9'
p1; 이런 부분은 os.environ 에서 읽어와주시는게 좋습니다. repo에 올리시면 안됩니다.

2022-01-06 08:23 UTC, AhnSeongHyun commented on app/models/models.py
> +    username: str
```suggestion
    user_name: str
```

2022-01-06 08:37 UTC, Jeldo requested changes

2022-01-06 08:37 UTC, Jeldo commented on app/api/auth.py
> +    return pwd_context.hash(password)
P2: 외부 모듈에서 사용되지 않는 private한 함수라면 앞에 underscore(_)를 붙이고 public한 함수 아래로 배치해주시면 좋을 것 같습니다.

2022-01-06 08:37 UTC, Jeldo commented on app/api/auth.py
> +def authenticate_user(username: str, password: str):
P2: 여기도 private하면 아래로 배치해주세요.

2022-01-06 08:37 UTC, Jeldo commented on app/api/auth.py
> +    credentials_exception = HTTPException(
P1: 예외는 다른 곳에 별도로 지정해서 사용하면 좋을 것 같아요.

2022-01-06 08:37 UTC, Jeldo commented on app/api/auth.py
> +async def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends()):
P2: 함수명을 `login`으로해도 좋을 것 같아요.

2022-01-06 08:37 UTC, Jeldo commented on app/service/user.py
> +    user.username = username
P2: User 모델이 변경되면 여기도 같이 user_name으로 변경부탁드려요

2022-01-06 10:19 UTC, Djangowon commented on app/models/models.py
> +    username: str
이전에 api/auth.py 에서 email, password를 파라미터로 받는 구조로 로직을 짰는데 OAuth2PasswordRequestForm 을 사용할 때 default 값이 username 으로 되어있어서 email로 적용 실패해 username 으로 수정했습니다. 만약 모델에서 user_name 으로 바꾸게 된다면 OAuth2PasswordRequestForm 안의 해당하는 라이브러리 변수명들도 user_name 으로 수정해서 적용해야 될 것 같습니다!
ask: 혹시 username이 아닌 email로 받고 싶을 경우 라이브러리 코드부터 전부 username 을 email로 바꿔서 적용하면 될까요?

2022-01-06 10:20 UTC, Djangowon commented on app/api/auth.py
> +SECRET_KEY = 'e9ba92fd-0660-4bc2-a90b-5121bdd67ca9'
환경변수 추가하여 수정했습니다. 감사합니다~!

2022-01-06 11:19 UTC, Djangowon commented on app/api/auth.py
> +async def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends()):
`login` 으로 수정했습니다.

2022-01-06 11:22 UTC, Djangowon commented on app/api/auth.py
> +    credentials_exception = HTTPException(
exeption 함수 따로 지정하여 호출하는 구조로 수정했습니다!

2022-01-06 13:07 UTC, Jeldo requested changes

2022-01-06 13:07 UTC, Jeldo commented on app/api/auth.py
> +    to_encode = data
P2: to_encode보다 `payload`가 더 적절할 것 같아요.

2022-01-07 00:28 UTC, szto requested changes

2022-01-07 00:28 UTC, szto commented on app/api/auth.py
> +    credentials_exception = get_user_exception()
p2: 함수 옮기시면서 처리를 하시긴 하시겠지만 exception 이면 사전에 굳이 변수에 할당하지 않으셔도 됩니다. raise 시에 get_user_exception()을 호출하는 것이 더 나아 보입니다. (현 시점에서)

2022-01-07 00:28 UTC, szto commented on app/api/auth.py
> +        username: str = payload.get('sub')
```suggestion
        username: Optional[str] = payload.get('sub', None)
```
p1: 아래 username 이 None일 수 있는 상황이라서 이렇게 해 주시는 것이 좋을것 같네요.

2022-01-07 00:28 UTC, szto commented on app/api/auth.py
> +    user = _get_user(username=token_data.username)
```suggestion
    user = _get_user(username=username)
```
p2: username 이 정의가 되어 있는데 token_data에 다시 접근해서 username을 호출하지 않아도 될 것 같아요. 혹시 이렇게 하시는 이유가 있을까요?

2022-01-07 00:28 UTC, szto commented on app/api/auth.py
> +        return UserInDB(**user_dict)
```suggestion
    user = session.query(User).filter(User.username == username).first()
    if username in user:
        user_dict = user[username]
        return UserInDB(**user_dict)
```
p1: 호출된 대상은 db 가 아니라 user 라서 변경해 주시는 것이 좋을것 같습니다. 
ask: username 은 db 에서 불러 오는 것이 아닌가요?

2022-01-07 00:28 UTC, szto commented on app/api/auth.py
> +def _get_user(username: str):
```suggestion
def _get_user(username: str) -> Optional[UserInDB]:
```
위에 처럼 해 주시는 것이 좋은데, db 에 없을 시 처리가 잘 되어 있는지 궁금하네요.

2022-01-07 21:14 UTC, szto requested changes
서비스 함수에서 return type 모두 달아 주세요~

2022-01-07 21:14 UTC, szto commented on app/service/auth.py
> +    user = get_user(username=token_data.username)
p1, ask: 여기를 TokenData 에 user_id 를 할당했다가 다시 username 으로 빼서 get_user 함수를 호출하시는 이유가 있을까요? TokenData 로 할당된 taken_data 안에 username attribute 가 존재하나요?

2022-01-07 21:14 UTC, szto commented on app/service/auth.py
> +    return current_user
ask: 이 함수는 사용하고 있지 않은것 가은데 미사용 함수이면 삭제해 주세요~

2022-01-07 21:14 UTC, szto commented on app/service/auth.py
> +pwd_context = CryptContext(schemes=['bcrypt'], deprecated='auto')
ask: 이 pwd_context가 여기에 정의된 이유가 있을까요? 광역적으로 사용하는 것이 아니라면 함수 안에 정의되어 있어야 합니다. 그렇지 않으면 패키지로 착각할 수 밖에 없을것 같습니다.

2022-01-10 05:28 UTC, Jeldo requested changes

2022-01-10 05:28 UTC, Jeldo commented on app/api/auth.py
> +    return {'access_token': access_token, 'token_type': 'bearer'}
응답을 JSONReponse로 주면 좋을 것 같은데, 다음 PR에서 진행해보시죵

2022-01-10 05:28 UTC, Jeldo commented on app/api/auth.py
> +    )
P2: 토큰 만료시각의 정의는 API보다는 create_access_token 함수 내부에서 정의&적용하면 좋아보입니다. API는 함수호출만하고 그대로 전달해주는 역할만 하면 될 것 같아요.

2022-01-10 05:28 UTC, Jeldo commented on app/service/user.py
> +    user.name = users.username
P2: 다른 코멘트에서 `user_name`으로 언급된것 같은데 반영 부탁드려요

2022-01-10 07:12 UTC, AhnSeongHyun approved these changes

2022-01-10 07:17 UTC, merged