feat: add post_account with oauth2
Djangowon/fastapi-test pull request #6
Opened 2022-01-10 07:28 UTC by Djangowon

### Summary

- 가계부 생성 기능 추가

### Story

- 가계부

### Changes

- bearer token을 통해 유저정보(user_id) 알 수 있음
- body 에 price, memo 를 담아 post 로 account 생성 가능
- 생성시 201 반환

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### Screenshots (Optional)

### How to test (Optional)
*How to test this PR*

2022-01-10 07:41 UTC, Jeldo requested changes

2022-01-10 07:41 UTC, Jeldo commented on app/api/account.py
> +    return {"message": "CREATE_SUCCESS"}
여기도 다음 PR에 리팩토링 진행하면서 JSONResponse로 반환하면 좋을 것 같아요.

2022-01-10 07:41 UTC, Jeldo commented on app/service/account.py
> +    print(payload)
P2: 디버깅용으로 사용한 출력은 삭제해주세요.

2022-01-10 07:41 UTC, Jeldo commented on app/service/account.py
> +    return
P2: return type이 Account인데 반환을 하고 있지 않습니다. 여기서 new_account를 반환하고, API쪽에서는 이를 response body에 넣어주면 될 것 같습니다.

2022-01-10 07:44 UTC, szto requested changes

2022-01-10 07:44 UTC, szto commented on app/service/account.py
> +    user_id = payload.get('id')
p2: token 을 받아서 service 단 가지 사용하지 말고 get_current_user 같은 함수를 만들어서 user 를 가져오는 형태로 구현이 되면 좋을것 같습니다.
https://fastapi.tiangolo.com/tutorial/security/get-current-user/

2022-01-10 07:44 UTC, szto commented on app/api/account.py
> +    return {"message": "CREATE_SUCCESS"}
p2: response_model 사용해서 account 정보를 넘겨서 출력해 주세요.

2022-01-10 12:34 UTC, Jeldo requested changes

2022-01-10 12:34 UTC, Jeldo commented on app/service/auth.py
> +    token_data = TokenData(user_id=user_id)
ASK: TokenData 클래스는 단순히 user_id를 감싼 클래스인데, 사용하는 이유가 궁금합니다. 별다른 이유가 없으면 그냥 user_id를 전달하면 좋을 것 같아요.

2022-01-10 12:34 UTC, Jeldo commented on app/service/account.py
> +    new_account.user_id = user.get("user_id")
P2: Account 객체 생성시 넣을 수 있는 필드는 생성자에서 파라미터로 전달해서 생성하는 편이 깔끔해서 좋을 것 같아요.
```suggestion
    user_id = user.get("user_id")
    new_account = Account(price=account.price, memo=account.memo, user_id=user_id)
```

2022-01-11 01:51 UTC, Jeldo approved these changes

2022-01-11 01:51 UTC, Jeldo commented
LGTM 고생하셨어요 👍

2022-01-11 03:58 UTC, merged