feat: add patch_account with oauth2
Djangowon/fastapi-test pull request #8
Opened 2022-01-11 05:48 UTC by Djangowon

### Summary

- 가계부 수정 기능 구현

### Story

- 가계부

### Changes

- 토큰 검증 후 해당 토큰의 유저정보 확인해 user_id 를 가진 account 의 price, memo 를 수정할 수 있음
- 성공시 200반환

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### Screenshots (Optional)

### How to test (Optional)
*How to test this PR*

2022-01-11 07:34 UTC, AhnSeongHyun requested changes

2022-01-11 08:42 UTC, Djangowon commented on app/api/account.py
> +async def patch_account(accounts: Account, token: str = Depends(get_current_user)):
네! 수정했습니다~! c0c0dc3

2022-01-11 08:42 UTC, Djangowon commented on app/service/account.py
> +    account = session.query(Account).filter(Account.id == accounts.id).first()
수정했습니다! c0c0dc3

2022-01-11 12:55 UTC, Jeldo requested changes

2022-01-11 12:55 UTC, Jeldo commented on app/service/account.py
> +        return account_not_found()
P2: account is None은 인자로 받은 account가 없는 경우인데, 클라이언트에서 업데이트에 사용할 가계부를 서버에게 전달했을 때, 그 가계부에 대한 포맷 검증은 API쪽에서하고, Service에서는 업데이트만 담당하는 것이 좋아보입니다.
그리고 다른 예외들은 raise 키워드로 예외를 던지고 있는데 여기서는 return을 하고있습니다. raise로 HTTPException을 던져야하지않나 싶습니다. 확인부탁드릴께요.
```suggestion
    if new_account is None:
        return account_not_found()
```

2022-01-11 12:55 UTC, Jeldo commented on app/service/account.py
> +    account.user_id = user.get("user_id")
ASK: 가계부의 user_id는 항상 동일할 것 같은데, user_id를 갱신하는 이유가 궁금합니당..

2022-01-12 07:15 UTC, Jeldo requested changes

2022-01-12 07:15 UTC, Jeldo commented on app/service/account.py
>      new_account = Account(price=account.price, memo=account.memo, user_id=user.get("user_id"))
P2: 이전 PR에서 제가 확인을 못한 것 같은데, 여기 리턴이 list 형태가 맞는지 확인부탁드릴께요. create_account로 가계부 생성을 하면 생성된 가계부만 반환되는게 맞을 것 같은데 여기서는 가계부 리스트를 반환하도록 타입 힌트가 적용이되어있네용.

2022-01-13 01:45 UTC, Jeldo requested changes

2022-01-13 01:45 UTC, Jeldo commented on app/api/account.py
> +        raise account_not_found()
ASK: 여기서 파라미터로 받는 account는 클라이언트의 요청을 통해 받는 가계부 아닌가요? 클라이언트에서 전달하는 가계부의 포맷이 잘못되었다면 not found 보다는 bad request 혹은 unprocessable entity 코드를 반환하는 것이 좋을 것 같아요.
[Ref1](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)
[Ref2](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)

2022-01-13 04:09 UTC, Jeldo commented on app/api/account.py
> +        raise account_not_found()
https://stackoverflow.com/questions/16133923/400-vs-422-response-to-post-of-data
여기 질답들이 도움이 될 것 같네요.
형식에 맞지 않는 요청인 경우 -> 400

2022-01-13 04:58 UTC, Jeldo requested changes

2022-01-13 04:58 UTC, Jeldo commented on app/api/account.py
> +    results = await update_account(account, token)
service의 update account 함수에서 DB 쿼리를 실행했을 때 가계부가 없다면 non found 예외를 던지는 것이 맞습니다.
이와는 별개로 api에서 클라이언트의 요청을 받았을 때 account에 대해 처리를 할 수 없다면 400 에러를 반환하는 것이라는 의미였습니다.

클라이언트 요청시
정상인 경우 -> 200
비정상인 경우
- 클라이언트 요청 자체가 문제인 경우 -> 400
- 없는 사용자의 경우 -> 404

2022-01-13 10:31 UTC, Jeldo approved these changes
변수 이름 코멘트 남긴 부분만 해결해주시고 머지해주세요. 선승인 남길께요~

2022-01-13 10:31 UTC, Jeldo commented on app/api/account.py
> +    results = await update_account(account, token)
```suggestion
    updated_account = await update_account(account, token)
```
P2: 단수형인 result 혹은 updated_account가 더 좋을 것 같습니다.

2022-01-13 11:20 UTC, merged